#####关键设置#####
log_level: "INFO" #日志等级[DEBUG/INFO]
March7thAssistant_path: "D:/StarRailTools/March7thAssistant/March7th Assistant.exe" #三月七助手控制台路径
mhy_launcher_path: "D:/MiHoYo/miHoYo Launcher/launcher.exe" #米哈游启动器路径
#####游戏——更新#####
game_update: True #是否更新游戏[True/False]
game_update_run_march7thAssistant: True #是否更新后运行三月七助手[True/False] 